-- 실습 11-9 토드와 SQL*PLUS로 LOCK 알아보기
SELECT * FROM DEPT_TCL;

-- 실습 11-10 토드와 SQL*PLUS로 LOCK 알아보기
UPDATE DEPT_TCL SET LOC='SEOUL'
 WHERE DEPTNO = 30;

SELECT * FROM DEPT_TCL;

-- 실습 11-11 토드와 SQL*PLUS로 LOCK 알아보기
UPDATE DEPT_TCL SET DNAME='DATABASE'
 WHERE DEPTNO = 30;

-- 실습 11-12 토드와 SQL*PLUS로 LOCK 알아보기
COMMIT;

-- 실습 11-13 토드와 SQL*PLUS로 LOCK 알아보기
SELECT * FROM DEPT_TCL;

-- 실습 11-14 토드와 SQL*PLUS로 LOCK 알아보기 - 세션 B(SQL*PLUS)
COMMIT;

-- 실습 11-15 토드와 SQL*PLUS로 LOCK 알아보기 - 세션 A(토드)
SELECT * FROM DEPT_TCL;