-- Q1. DEPT_CONST 테이블과 EMP_CONST 테이블을 다음과 같은 특성 및 제약 조건을 지정하여 만들어 보세요.
-- ① DEPT_CONST 테이블
CREATE TABLE DEPT_CONST (
    DEPTNO  NUMBER(2) CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY,
    DNAME   VARCHAR2(14) CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE,
    LOC     VARCHAR2(13) CONSTRAINT DEPTCONST_LOC_NN NOT NULL
);
DESC DEPT_CONST;

-- ② EMP_CONST 테이블
CREATE TABLE EMP_CONST (
    EMPNO   NUMBER(4) CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY,
    ENAME   VARCHAR2(10) CONSTRAINT EMPCONST_ENAME_NN NOT NULL,
    JOB     VARCHAR2(9),
    TEL     VARCHAR2(20) CONSTRAINT EMPCONST_TEL_UNQ UNIQUE,
    HIREDATE    DATE,
    SAL     NUMBER(7,2) CONSTRAINT EMPCONST_SAL_CHK CHECK (LENGTH(SAL) >1000 AND (SAL) < 9999),
    COMM    NUMBER(7,2),
    DEPTNO  NUMBER(2) CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST(DEPTNO)
);

-- ③ 테이블 생성 후 데이터 사전 뷰를 사용하여 다음과 같이 두 테이블의 제약 조건을 확인해 보세요.
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('EMP_CONST', 'DEPT_CONST')
ORDER BY CONSTRAINT_NAME;