-- 실습 6-23 SYSDATE 함수를 사용하여 날짜 출력하기
SELECT SYSDATE AS NOW,
        SYSDATE-1 AS YESTERDAY,
        SYSDATE+1 AS TOMORROW
FROM DUAL;

-- 실습 6-24 SYSDATE와 ADD_MONTHS 함수로 3개월 후 날짜 구하기
SELECT SYSDATE,
        ADD_MONTHS(SYSDATE, 3)
FROM DUAL;

-- 실습 6-25 입사 10주년이 되는 사원들 데이터 출력하기
SELECT EMPNO, ENAME, HIREDATE,
        ADD_MONTHS(HIREDATE, 120) AS WORK10YEAR
FROM EMP;

-- 실습 6-26 입사 32년 미만인 사원 데이터 출력하기
SELECT EMPNO, ENAME, HIREDATE, SYSDATE
FROM EMP
WHERE ADD_MONTHS(HIREDATE, 384) > SYSDATE;

-- 1분 복습. SYSDATE와 ADD_MONTHS 함수를 사용하여 현재 날짜와 6개월 후 날짜가 출력되도록
-- SQL문의 빈칸을 채워보세요.
SELECT SYSDATE,
        ADD_MONTHS(SYSDATE, 6)
FROM DUAL;

-- 실습 6-27 HIREDATE와 SYSDATE 사이의 개월 수를 MONTHS_BETWEEN 함수로 출력하기
SELECT EMPNO, ENAME, HIREDATE, SYSDATE,
        MONTHS_BETWEEN(HIREDATE, SYSDATE) AS MONTHS1,
        MONTHS_BETWEEN(SYSDATE, HIREDATE) AS MONTHS2,
        TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)) AS MONTHS3
FROM EMP;

-- 실습 6-28 NEXT_DAY, LAST_DAY 함수를 사용하여 출력하기
SELECT SYSDATE,
        NEXT_DAY(SYSDATE, '월요일'),
        LAST_DAY(SYSDATE)
FROM DUAL;

-- 실습 6-29 ROUND 함수 사용하여 날짜 데이터 출력하기
SELECT SYSDATE,
        ROUND(SYSDATE, 'CC') AS FORMAT_CC,
        ROUND(SYSDATE, 'YYYY') AS FORMAT_YYYY,
        ROUND(SYSDATE, 'Q') AS FORMAT_Q,
        ROUND(SYSDATE, 'DDD') AS FORMAT_DDD,
        ROUND(SYSDATE, 'HH') AS FORMAT_HH
FROM DUAL;

-- 실습 6-30 TRUNC 함수를 사용하여 날짜 데이터 출력하기
SELECT SYSDATE,
        TRUNC(SYSDATE, 'CC') AS FORMAT_CC,
        TRUNC(SYSDATE, 'YYYY') AS FORMAT_YYYY,
        TRUNC(SYSDATE, 'Q') AS FORMAT_Q,
        TRUNC(SYSDATE, 'DDD') AS FORMAT_DDD,
        TRUNC(SYSDATE, 'HH') AS FORMAT_HH
FROM DUAL;
