-- 실습 15-14 SYSTEM 계정으로 ROLESTUDY 롤 생성 및 권한 부여하기
CONN SYSTEM/1234

CREATE ROLE C##ROLESTUDY;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM
TO C##ROLESTUDY;

-- 실습 15-15 ORCLSTUDY 사용자에게 롤(ROLESTUDY)부여하기
GRANT C##ROLESTUDY TO C##ORCLSTUDY;

-- 실습 15-16 ORCLSTUDY에 부여된 롤과 권한 확인하기
CONN C##ORCLSTUDY/ORACLE
SELECT * FROM USER_SYS_PRIVS;
SELECT * FROM USER_ROLE_PRIVS;