-- 실습 5-18 BEETWEEN A AND B 연산자를 사용하여 출력하기
SELECT * FROM EMP
 WHERE SAL BETWEEN 2000 AND 3000;

-- 실습 5-19 BEETWEEN A AND B 연산자와 NOT 연산자를 사용하여 출력하기
SELECT * FROM EMP
 WHERE SAL NOT BETWEEN 2000 AND 3000;

-- 실습 5-20 LIKE 연산자 사용하여 출력하기
SELECT * FROM EMP
 WHERE ENAME LIKE 'S%';

-- 실습 5-21 사원 이름의 두 번째 글자가 L인 사원만 출력하기
SELECT * FROM EMP
 WHERE ENAME LIKE '_L%';

-- 실습 5-22 사원 이름에 AM이 포함되어 있는 사원 데이터만 출력하기
SELECT * FROM EMP
WHERE ENAME LIKE '%AM%';

-- 실습 5-23 사원 이름에 AM이 포함되어 있지 않은 사원 데이터 출력하기
SELECT * FROM EMP
WHERE ENAME NOT LIKE '%AM%';

-- 실습 5-24 별칭을 사용하여 열 이름 출력하기
SELECT ENAME, SAL, SAL*12+COMM AS ANNSAL, COMM
 FROM EMP;

-- 실습 5-25 등가 비교 연산자로 NULL 비교하기
SELECT * FROM EMP
WHERE COMM = NULL;

-- 실습 5-26 IS NULL 연산자를 사용하여 출력하기
SELECT * FROM EMP
WHERE COMM IS NULL;

-- 실습 5-27 직속 상관이 있는 사원 데이터만 출력하기
SELECT * FROM EMP
WHERE MGR IS NOT NULL;

-- 실습 5-28 AND 연산자와 IS NULL 연산자 사용하기
SELECT * FROM EMP
WHERE SAL > NULL
AND COMM IS NULL;

-- 실습 5-29 OR 연산자와 IS NULL 연산자 사용하기
SELECT * FROM EMP
WHERE SAL > NULL
OR COMM IS NULL;

-- 실습 5-30 집합 연산자(UNION)를 사용하여 출력하기
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 20;

-- 실습 5-31 집합 연산자(UNION)를 사용하여 출력하기(출력 열 개수가 다를 때)
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE DEPTNO = 20;

-- 실습 5-32 집합 연산자(UNION)를 사용하여 출력하기(출력 열의 자료형이 다를 때)
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT ENAME, EMPNO, DEPTNO, SAL
FROM EMP
WHERE DEPTNO = 20;

-- 실습 5-33 집합 연산자(UNION)를 사용하여 출력하기(출력 열 개수와 자료형이 같을 때
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT SAL, JOB, DEPTNO, SAL
FROM EMP
WHERE DEPTNO = 20;

-- 실습 5-34 집합 연산자(UNION)를 사용하여 출력하기(출력 결과 테이터가 같을 때)
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

-- 실습 5-35 집합 연산자(UNION ALL)를 사용하여 출력하기(출력 결과 테이터가 같을 때
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

-- 실습 5-36 집합 연산자(MINUS)를 사용하여 출력하기
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

-- 실습 5-37 집합 연산자(INTERSECT)를 사용하여 출력하기
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;
