-- 실습 13-26 DEPT 테이블을 사용하여 DEPT_SEQUENCE 테이블 생성하기
CREATE TABLE DEPT_SEQUENCE
AS SELECT * FROM DEPT
WHERE 1 <> 1;

SELECT * FROM DEPT_SEQUENCE;

-- 실습 13-27 시퀀스 생성하기
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
 INCREMENT BY 10
 START WITH 10
 MAXVALUE 90
 MINVALUE 0
 NOCYCLE
 CACHE 2;
 
 -- 실습 13-28 생성한 시퀀스 확인하기
 SELECT * FROM USER_SEQUENCES;
 
 -- 실습 13-29 시퀀스에서 생성한 순번을 사용한 INSERT문 실행하기
 INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
 VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');
 
 SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;
 
 -- 실습 13-30 가장 마지막으로 생성된 시퀀스 확인하기
 SELECT SEQ_DEPT_SEQUENCE.CURRVAL
 FROM DUAL;
 
 -- 실습 13-31 시퀀스에서 생성한 순번을 반복 사용하여 INSERT문 실행하기
 INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
 VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');
 
  SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;
  
  -- 실습 13-32 시퀀스 옵션 수정하기
  ALTER SEQUENCE SEQ_DEPT_SEQUENCE
   INCREMENT BY 3
   MAXVALUE 99
   CYCLE;
   
-- 실습 13-33 옵션을 수정한 시퀀스 조회하기
SELECT * FROM USER_SEQUENCES;

-- 실습 13-34 수정한 시퀀스를 사용하여 INSERT문 실행하기
 INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
 VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');
 
  SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;
  
-- 실습 13-35 CYCLE 옵션을 사용한 시퀀스 최댓값 도달 후 수행 결과 확인하기
 INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
 VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');
 
  SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;

-- 실습 13-36 시퀀스 삭제 후 확인하기
DROP SEQUENCE SEQ_DEPT_SEQUENCE;

SELECT * FROM USER_SEQUENCES;

-- 실습 13-37 권한 부여하기(SQL*PLUS)
SQLPLUS SYSTEM/1234

GRANT CREATE SYNONYM TO SCOTT;

GRANT CREATE PUBLIC SYNONYM TO SCOTT;

-- 실습 13-38 EMP 테이블의 동의어 생성하기(토드)
CREATE SYNONYM E
FOR EMP;

-- 실습 13-39 E 테이블 전체 내용 조회하기(토드)
SELECT * FROM E;

-- 실습 13-40 동의어 삭제하기(토드)
DROP SYNONYM E;
