-- 실습 7-16 집합 연산자를 사용하여 각 부서별 평균 급여 출력하기
SELECT AVG(SAL), '10' AS DEPTNO FROM EMP WHERE DEPTNO = 10
UNION ALL
SELECT AVG(SAL), '20' AS DEPTNO FROM EMP WHERE DEPTNO = 20
UNION ALL
SELECT AVG(SAL), '30' AS DEPTNO FROM EMP WHERE DEPTNO = 30;

-- 실습 7-17 GROUP BY를 사용하여 부서별 평균 급여 출력하기
SELECT AVG(SAL), DEPTNO
FROM EMP
GROUP BY DEPTNO;

-- 실습 7-18 부서 번호 및 직책별 평균 급여로 정렬하기
SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

-- 1분 복습. GROUP BY 절을 사용하여 부서 번호별 평균 추가 수당을 출력하도록
-- 다음 SQL의 빈칸을 채워 보세요.
SELECT AVG(COMM), DEPTNO
FROM EMP
GROUP BY DEPTNO;

-- 실습 7-19 GROUP BY절에 없는 열을 SELECT절에 포함했을 경우
SELECT ENAME, DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO;