-- 실습 19-31 EMP_TRG 테이블 생성하기
CREATE TABLE EMP_TRG
    AS SELECT * FROM EMP;
    
-- 실습 19-32 DML 실행 전에 수행할 트리거 생성하기
CREATE OR REPLACE TRIGGER TRG_EMP_NODML_WEEKEND
BEFORE
INSERT OR UPDATE OR DELETE ON EMP_TRG
BEGIN
    IF TO_CHAR(SYSDATE, 'DY') IN ('토', '일') THEN
        IF INSERTING THEN
            RAISE_APPLICATION_ERROR(-20000, '주말 사원정보 추가 불가');
        ELSIF UPDATING THEN
            RAISE_APPLICATION_ERROR(-20001, '주말 사원정보 추가 불가');
        ELSIF DELETING THEN
            RAISE_APPLICATION_ERROR(-20002, '주말 사원정보 추가 불가');
        ELSE
            RAISE_APPLICATION_ERROR(-20003, '주말 사원정보 추가 불가');
        END IF;
    END IF;
END;
/

-- 실습 19-33 평일 날짜로 EMP_TRG테이블 UPDATE하기
UPDATE EMP_TRG SET SAL = 3500 WHERE EMPNO = 7788;

-- 실습 19-34 주말 날짜에 EMP_TRG테이블 UPDATE하기
UPDATE EMP_TRG SET SAL = 3500 WHERE EMPNO = 7788;

-- 실습 19-35 EMP_TRG_LOG 테이블 생성하기
CREATE TABLE EMP_TRG_LOG(
    TABLENAME VARCHAR2(10),  -- DML이 수행된 테이블 이름
    DML_TYPE VARCHAR2(10),   -- DML 명령어 종류
    EMPNO NUMBER(4),         -- DML 대상이 된 사원번호
    USER_NAME VARCHAR2(30),  -- DML을 수행한 USER 이름
    CHANGE_DATE DATE         -- DML이 수행된 날짜
);

-- 실습 19-36 DML 실행 후 수행할 트리거 생성하기
CREATE OR REPLACE TRIGGER TRG_EMP_LOG
AFTER
INSERT OR UPDATE OR DELETE ON EMP_TRG
FOR EACH ROW

BEGIN

    IF INSERTING THEN
        INSERT INTO EMP_TRG_LOG
        VALUES('EMP_TRG', 'INSERT', :NEW.EMPNO,
                SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSDATE);
                
    ELSIF UPDATING THEN
        INSERT INTO EMP_TRG_LOG
        VALUES('EMP_TRG', 'UPDATE', :OLD.EMPNO,
                SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSDATE);
                
    ELSIF DELETING THEN
        INSERT INTO EMP_TRG_LOG
        VALUES('EMP_TRG', 'DELETE', :NEW.EMPNO,
                SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSDATE);
   END IF;
END;
/

-- 실습 19-37 EMP_TRG 테이블에 INSERT 실행하기
INSERT INTO EMP_TRG
VALUES(9999, 'TESTEMP', 'CLERK', 7788, TO_DATE('2018-03-03', 'YYYY-MM-DD'), 1200, NULL, 20);

-- 실습 19-38 EMP_TRG 테이블에 INSERT 실행하기(COMMIT하기)
COMMIT;

-- 실습 19-39 EMP_TRG 테이블의 INSERT 확인하기
SELECT * FROM EMP_TRG;

-- 실습 19-40 EMP_TRG_LOG 테이블의 INSERT 기록 확인하기
SELECT
    * FROM emp_trg_log;
    
-- 실습 19-41 EMP_TRG 테이블에 UPDATE 실행하기
UPDATE EMP_TRG
SET SAL = 1300
WHERE MGR = 7788;

-- 실습 19-41 EMP_TRG 테이블에 INSERT 실행하기(COMMIT하기)
COMMIT;

-- 실습 19-42 USER_TRIGGERS로 트리거 정보 조회하기
SELECT TRIGGER_NAME, TRIGGER_TYPE, TRIGGERING_EVENT, TABLE_NAME, STATUS FROM USER_TRIGGERS;